apiVersion: v1 
kind: Pod
metadata:
  name: ubuntu
spec:
      containers:
      - name: ubuntu-ctr
        image: ubuntu
        ports:
        - containerPort: 80
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]