apiVersion: v1 
kind: Pod
metadata:
  name: netcoreconsole-app2
spec:
      containers:
      - name: netcoreconsole-app2
        image: paraspatidardocker/netcoreconsole
        ports:
        - containerPort: 80
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]