apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-hello-world-debug
spec:
  selector:
    matchLabels:
      app: nodejs-hello-world-debug
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nodejs-hello-world-debug
    spec:
      containers:
      - name: node-hello-world
        image: paraspatidardocker/node-hello-world
        ports:
        - containerPort: 80
    