apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: netcore-deployment-debug
spec:
  selector:
    matchLabels:
      app: netcoredockerwebapp-debug
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: netcoredockerwebapp-debug
    spec:
      containers:
      - name: netcoredockerwebapp-debug
        image: paraspatidardocker/netcoredockerwebapp-debug
        ports:
        - containerPort: 80